"""Shared fixtures for the bin/spud test suite.

Every database, render target and settings file a test touches lives under a
tempfile directory: a Home is a temporary SPUD_HOME with its own copy of
spud.config.json. Nothing here writes into the repository.
"""

import atexit
import importlib.machinery
import importlib.util
import json
import os
import shutil
import sqlite3
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

# The suite must leave no bytecode in the repo: bin/spud is loaded as a module
# by the parser tests, and `-I -S` does not read PYTHONDONTWRITEBYTECODE.  The
# first test module unittest imports is compiled before this line runs, so the
# cache directories are also removed when the interpreter exits.
sys.dont_write_bytecode = True

REPO = Path(__file__).resolve().parent.parent


def _remove_bytecode():
    for cache in (REPO / "bin" / "__pycache__", REPO / "tests" / "__pycache__"):
        shutil.rmtree(cache, ignore_errors=True)


atexit.register(_remove_bytecode)

SPUD = REPO / "bin" / "spud"
CONFIG = REPO / "spud.config.json"
MARKER = "<!-- generated by spud from .spud/ledger.db; edit with the spud CLI -->"

# Exit codes the CLI promises.
EXIT_OK = 0
EXIT_ERROR = 1
EXIT_USAGE = 2
EXIT_OWNERSHIP = 3
EXIT_LIMIT = 4
EXIT_TRANSITION = 5
EXIT_CONFLICT = 6


def real_config():
    with open(CONFIG, encoding="utf-8") as f:
        return json.load(f)


def load_spud_module():
    """Import bin/spud as a module (it has no .py suffix) for parser unit tests."""
    loader = importlib.machinery.SourceFileLoader("spud", str(SPUD))
    spec = importlib.util.spec_from_loader("spud", loader)
    module = importlib.util.module_from_spec(spec)
    loader.exec_module(module)
    return module


class Home:
    """A temporary SPUD_HOME with a config file; runs the CLI against it."""

    def __init__(self, config=None):
        self._tmp = tempfile.TemporaryDirectory(prefix="spud-test-")
        self.path = Path(self._tmp.name).resolve()
        self.config = config if config is not None else real_config()
        with open(self.path / "spud.config.json", "w", encoding="utf-8") as f:
            json.dump(self.config, f, indent=2)
        self.env = dict(os.environ)
        self.env["SPUD_HOME"] = str(self.path)
        # `member new` records the session its Bash runs in (SPD-018): a suite run from a Claude Code session must
        # not stamp that live session on scratch rows, so a test that wants a session names it.
        self.env.pop("CLAUDE_CODE_SESSION_ID", None)
        self.db = self.path / ".spud" / "ledger.db"

    def cleanup(self):
        self._tmp.cleanup()

    def run(self, *args, check=True, actor=None, stdin=None):
        cmd = [sys.executable, "-I", "-S", str(SPUD)]
        if actor is not None:
            cmd += ["--as", actor]
        cmd += [str(a) for a in args]
        proc = subprocess.run(cmd, capture_output=True, text=True, env=self.env, input=stdin)
        if check and proc.returncode != 0:
            raise AssertionError(
                "spud %s exited %d\nstdout: %s\nstderr: %s"
                % (" ".join(str(a) for a in args), proc.returncode, proc.stdout, proc.stderr)
            )
        return proc

    def json(self, *args, actor=None, check=True, stdin=None):
        proc = self.run("--json", *args, actor=actor, check=check, stdin=stdin)
        try:
            return json.loads(proc.stdout)
        except json.JSONDecodeError as e:
            raise AssertionError("not JSON: %r (stderr %r)" % (proc.stdout, proc.stderr)) from e

    def init(self):
        return self.json("init")

    def connect(self):
        con = sqlite3.connect(self.db, timeout=5)
        con.row_factory = sqlite3.Row
        return con

    def scalar(self, sql, *params):
        con = self.connect()
        try:
            row = con.execute(sql, params).fetchone()
            return None if row is None else row[0]
        finally:
            con.close()

    def rows(self, sql, *params):
        con = self.connect()
        try:
            return [dict(r) for r in con.execute(sql, params).fetchall()]
        finally:
            con.close()

    def write_settings(self, data):
        p = self.path / ".claude" / "settings.json"
        p.parent.mkdir(parents=True, exist_ok=True)
        with open(p, "w", encoding="utf-8") as f:
            json.dump(data, f, indent=2)
            f.write("\n")
        return p

    def write_config(self, config):
        """Rewrite the home's spud.config.json (the CLI reads it on every run)."""
        self.config = config
        with open(self.path / "spud.config.json", "w", encoding="utf-8") as f:
            json.dump(config, f, indent=2)

    def hook(self, event, payload):
        """Run `spud hook <event>` with the payload (a dict, or raw text) on stdin."""
        stdin = payload if isinstance(payload, str) else json.dumps(payload)
        proc = self.run("hook", event, check=False, stdin=stdin)
        return HookResult(proc.returncode, proc.stdout, proc.stderr)

    @property
    def spool(self):
        return self.path / ".spud" / "hook-errors.jsonl"


class HookResult:
    """What a hook run produced: exit code, stdout (parsed as JSON when it is), stderr."""

    def __init__(self, code, stdout, stderr):
        self.code = code
        self.stdout = stdout
        self.stderr = stderr
        self.json = None
        if stdout.strip():
            try:
                self.json = json.loads(stdout)
            except json.JSONDecodeError:
                self.json = None

    @property
    def decision(self):
        """PreToolUse: the permissionDecision, or None when the hook stayed silent."""
        if not self.json:
            return None
        return self.json.get("hookSpecificOutput", {}).get("permissionDecision")

    @property
    def reason(self):
        if not self.json:
            return ""
        return self.json.get("hookSpecificOutput", {}).get("permissionDecisionReason") or self.json.get("reason") or ""

    @property
    def context(self):
        if not self.json:
            return ""
        return self.json.get("hookSpecificOutput", {}).get("additionalContext") or ""

    def __repr__(self):
        return "HookResult(code=%r, stdout=%r, stderr=%r)" % (self.code, self.stdout, self.stderr)


class SpudTestCase(unittest.TestCase):
    """A test case with a fresh initialised Home per test."""

    config = None

    def setUp(self):
        self.home = Home(config=self.config)
        self.addCleanup(self.home.cleanup)
        self.home.init()

    # Small builders used across files.
    def new_ticket(self, title="A ticket", **kw):
        args = ["ticket", "new", "--title", title]
        for k, v in kw.items():
            if isinstance(v, (list, tuple)):
                for item in v:
                    args += ["--" + k.replace("_", "-"), item]
            else:
                args += ["--" + k.replace("_", "-"), v]
        return self.home.json(*args, actor="spud")["ticket"]

    def new_member(self, ticket, actor="spud", persona="scout", model="haiku", **kw):
        kw.setdefault("brief", "Do the thing.")
        args = ["member", "new", "--ticket", ticket, "--persona", persona, "--model", model]
        for k, v in kw.items():
            if isinstance(v, (list, tuple)):
                for item in v:
                    args += ["--" + k.replace("_", "-"), item]
            else:
                args += ["--" + k.replace("_", "-"), v]
        return self.home.json(*args, actor=actor)["member"]


def normalize_markdown(text):
    """The acceptance test's allowed differences: marker line, trailing
    whitespace, runs of blank lines (and blank lines at either end)."""
    out = []
    for line in text.splitlines():
        if line.strip() == MARKER:
            continue
        line = line.rstrip()
        if line == "" and out and out[-1] == "":
            continue
        out.append(line)
    while out and out[0] == "":
        out.pop(0)
    while out and out[-1] == "":
        out.pop()
    return "\n".join(out) + "\n"


# A ticket note's ## Team section is generated from the members table alone since SPD-010
# (docs/design/2026-09-12-team-card.md): a table, the member tree carrying each member's
# worked-on sentence, the embedded Team view.  The round trips compare it by the rule of the
# spec's section 8.3 rather than byte for byte.
TEAM_TABLE_HEADER = "| Member | ID | Persona | Model | Status | Run | Tokens | Cost (list) | Tools |"  # Cost (list) since SPD-013
TEAM_TABLE_DELIMITER = "|---|---|---|---|---|---|---|---|---|"
TEAM_VIEW_EMBED = "![[Fleet.base#Team]]"
WORKED_ON_SUFFIX = " — "


def split_team_section(text):
    """A note without the body of its `## Team` section (the heading line stays), and that body;
    (text, None) for a note that has no such section."""
    lines = text.split("\n")
    if "## Team" not in lines:
        return text, None
    start = lines.index("## Team") + 1
    end = start
    while end < len(lines) and not lines[end].startswith("## "):
        end += 1
    return "\n".join(lines[:start] + lines[end:]), "\n".join(lines[start:end])


def team_section_problems(source, rendered):
    """What is wrong with a rendered `## Team` body against the body it was imported from, [] when
    nothing: the tree lines (lines opening `- [[`), each without its ` — …` suffix, equal the
    source's in order; every source tree line that has a suffix is rendered unchanged; a section
    with members starts with the table header and delimiter and ends with the embed line, and a
    section without members is empty."""

    def tree(text):
        return [line.rstrip() for line in text.split("\n") if line.lstrip().startswith("- [[")]

    def bare(line):
        return line.split(WORKED_ON_SUFFIX, 1)[0]

    want, got = tree(source), tree(rendered)
    problems = []
    if [bare(line) for line in got] != [bare(line) for line in want]:
        problems.append("the tree lines without their suffixes differ: source %r, rendered %r" % ([bare(l) for l in want], [bare(l) for l in got]))
    for i, line in enumerate(want):
        if WORKED_ON_SUFFIX in line and (i >= len(got) or got[i] != line):
            problems.append("the source tree line %r is not rendered unchanged" % line)
    lines = [line.rstrip() for line in rendered.strip("\n").split("\n")] if rendered.strip() else []
    if want or got:
        if lines[:2] != [TEAM_TABLE_HEADER, TEAM_TABLE_DELIMITER]:
            problems.append("the section does not start with the table header and delimiter: %r" % lines[:2])
        if lines[-1:] != [TEAM_VIEW_EMBED]:
            problems.append("the section does not end with the embed line: %r" % lines[-1:])
    elif lines:
        problems.append("a ticket without members renders an empty section, not %r" % rendered)
    return problems
