"""Shared fixtures for the bin/spud test suite.

Every database, render target and settings file a test touches lives under a
tempfile directory: a Home is a temporary SPUD_HOME with its own copy of
spud.config.json. Nothing here writes into the repository.
"""

import atexit
import importlib.machinery
import importlib.util
import json
import os
import shutil
import sqlite3
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

# The suite must leave no bytecode in the repo: bin/spud_ledger.py is loaded as a
# module by the unit tests, and `-I -S` does not read PYTHONDONTWRITEBYTECODE.  (A
# CLI run caches it under its scratch SPUD_HOME's .spud/pycache/, never here.)  The
# first test module unittest imports is compiled before this line runs, so the
# cache directories are also removed when the interpreter exits.
sys.dont_write_bytecode = True

REPO = Path(__file__).resolve().parent.parent


def _remove_bytecode():
    for cache in (REPO / "bin" / "__pycache__", REPO / "tests" / "__pycache__"):
        shutil.rmtree(cache, ignore_errors=True)


atexit.register(_remove_bytecode)

SPUD = REPO / "bin" / "spud"  # the launcher: what the hooks, the allow rules and every test run
PROGRAM = REPO / "bin" / "spud_ledger.py"  # the program it loads (SPD-016)
CONFIG = REPO / "spud.config.json"
MARKER = "<!-- generated by spud from .spud/ledger.db; edit with the spud CLI -->"

# Exit codes the CLI promises.
EXIT_OK = 0
EXIT_ERROR = 1
EXIT_USAGE = 2
EXIT_OWNERSHIP = 3
EXIT_LIMIT = 4
EXIT_TRANSITION = 5
EXIT_CONFLICT = 6


def real_config():
    with open(CONFIG, encoding="utf-8") as f:
        return json.load(f)


def load_spud_module():
    """Import the program, bin/spud_ledger.py, for unit tests (bin/spud is its launcher since SPD-016)."""
    loader = importlib.machinery.SourceFileLoader("spud_ledger", str(PROGRAM))
    spec = importlib.util.spec_from_loader("spud_ledger", loader)
    module = importlib.util.module_from_spec(spec)
    loader.exec_module(module)
    return module


class Home:
    """A temporary SPUD_HOME with a config file; runs the CLI against it."""

    def __init__(self, config=None, name=None):
        self._tmp = tempfile.TemporaryDirectory(prefix="spud-test-")
        self.path = Path(self._tmp.name).resolve()
        if name is not None:  # a home whose own directory has this name (SPD-029: a non-ASCII home, spelled NFC)
            self.path = self.path / name
            self.path.mkdir()
        self.config = config if config is not None else real_config()
        with open(self.path / "spud.config.json", "w", encoding="utf-8") as f:
            json.dump(self.config, f, indent=2)
        self.env = dict(os.environ)
        self.env["SPUD_HOME"] = str(self.path)
        # `member new` records the session its Bash runs in (SPD-018): a suite run from a Claude Code session must
        # not stamp that live session on scratch rows, so a test that wants a session names it.
        self.env.pop("CLAUDE_CODE_SESSION_ID", None)
        # SPD-014: the hooks read the session's launch directory from CLAUDE_PROJECT_DIR, which a suite run from a Claude
        # Code session inherits; a test that wants one sets it.  `project install` writes user-scope files and the home
        # pointer: both go under this scratch home, never into ~/.claude or ~/.config/spud.
        self.env.pop("CLAUDE_PROJECT_DIR", None)
        self.env["SPUD_USER_CLAUDE_DIR"] = str(self.path / ".user-claude")
        self.env["SPUD_CONFIG_DIR"] = str(self.path / ".user-config")
        self.db = self.path / ".spud" / "ledger.db"

    def cleanup(self):
        self._tmp.cleanup()

    def run(self, *args, check=True, actor=None, stdin=None):
        cmd = [sys.executable, "-I", "-S", str(SPUD)]
        if actor is not None:
            cmd += ["--as", actor]
        cmd += [str(a) for a in args]
        proc = subprocess.run(cmd, capture_output=True, text=True, env=self.env, input=stdin)
        if check and proc.returncode != 0:
            raise AssertionError(
                "spud %s exited %d\nstdout: %s\nstderr: %s"
                % (" ".join(str(a) for a in args), proc.returncode, proc.stdout, proc.stderr)
            )
        return proc

    def json(self, *args, actor=None, check=True, stdin=None):
        proc = self.run("--json", *args, actor=actor, check=check, stdin=stdin)
        try:
            return json.loads(proc.stdout)
        except json.JSONDecodeError as e:
            raise AssertionError("not JSON: %r (stderr %r)" % (proc.stdout, proc.stderr)) from e

    def init(self):
        return self.json("init")

    def connect(self):
        con = sqlite3.connect(self.db, timeout=5)
        con.row_factory = sqlite3.Row
        return con

    def scalar(self, sql, *params):
        con = self.connect()
        try:
            row = con.execute(sql, params).fetchone()
            return None if row is None else row[0]
        finally:
            con.close()

    def rows(self, sql, *params):
        con = self.connect()
        try:
            return [dict(r) for r in con.execute(sql, params).fetchall()]
        finally:
            con.close()

    def write_settings(self, data):
        p = self.path / ".claude" / "settings.json"
        p.parent.mkdir(parents=True, exist_ok=True)
        with open(p, "w", encoding="utf-8") as f:
            json.dump(data, f, indent=2)
            f.write("\n")
        return p

    def write_config(self, config):
        """Rewrite the home's spud.config.json (the CLI reads it on every run)."""
        self.config = config
        with open(self.path / "spud.config.json", "w", encoding="utf-8") as f:
            json.dump(config, f, indent=2)

    def hook(self, event, payload):
        """Run `spud hook <event>` with the payload (a dict, or raw text) on stdin."""
        stdin = payload if isinstance(payload, str) else json.dumps(payload)
        proc = self.run("hook", event, check=False, stdin=stdin)
        return HookResult(proc.returncode, proc.stdout, proc.stderr)

    @property
    def spool(self):
        return self.path / ".spud" / "hook-errors.jsonl"


GIT_IDENTITY = {"GIT_AUTHOR_NAME": "Spud", "GIT_AUTHOR_EMAIL": "spud@example.invalid", "GIT_COMMITTER_NAME": "Spud", "GIT_COMMITTER_EMAIL": "spud@example.invalid"}


def isolated_git_env(base=None):
    """An environment in which git reads none of this machine's configuration (SPD-014): no global or system config, no
    global excludes file (Claude Code adds `**/.claude/settings.local.json` there), no signing, a fixed identity."""
    env = {k: v for k, v in (os.environ if base is None else base).items() if not k.startswith("GIT_")}
    env.update(GIT_CONFIG_GLOBAL="/dev/null", GIT_CONFIG_NOSYSTEM="1", GIT_CONFIG_COUNT="2",
               GIT_CONFIG_KEY_0="core.excludesFile", GIT_CONFIG_VALUE_0="/dev/null",
               GIT_CONFIG_KEY_1="commit.gpgsign", GIT_CONFIG_VALUE_1="false", **GIT_IDENTITY)
    return env


def git(repo, *args, check=True):
    proc = subprocess.run(["git", "-C", str(repo), *[str(a) for a in args]], capture_output=True, text=True, env=isolated_git_env())
    if check and proc.returncode != 0:
        raise AssertionError("git %s in %s exited %d: %s" % (" ".join(str(a) for a in args), repo, proc.returncode, proc.stderr))
    return proc.stdout


class RepoMixin:
    """Scratch git repositories beside a SpudTestCase's home (SPD-014), and the CLI run from a directory in a session."""

    def scratch_dir(self, prefix="spud-repo-"):
        path = Path(tempfile.mkdtemp(prefix=prefix)).resolve()  # /var is /private/var: roots are compared resolved
        self.addCleanup(shutil.rmtree, path, True)
        return path

    def make_repo(self, prefix="other-", branch="main", origin=False):
        repo = self.scratch_dir(prefix)
        git(repo, "init", "-q", "-b", branch)
        git(repo, "commit", "-q", "--allow-empty", "-m", "root")
        if origin:
            bare = self.scratch_dir(prefix + "origin-")
            git(bare, "init", "-q", "--bare", "-b", branch)
            git(repo, "remote", "add", "origin", bare)
            git(repo, "push", "-q", "origin", branch)
            git(repo, "remote", "set-head", "origin", branch)
            self.origin = bare
        return repo

    def add_worktree(self, repo, name, inside=False):
        path = repo / ".claude" / "worktrees" / name if inside else repo.parent / ("%s-%s" % (repo.name, name))
        self.addCleanup(shutil.rmtree, path, True)
        git(repo, "worktree", "add", "-q", "-b", ("worktree-" + name) if inside else name, path)
        return path

    def cli(self, *args, actor=None, cwd=None, session=None, check=True, stdin=None, env=None):
        """bin/spud against the scratch home from `cwd` (default the home), in `session` (None: outside every session), with
        git isolated from this machine's configuration."""
        e = isolated_git_env(self.home.env)
        e.pop("CLAUDE_CODE_SESSION_ID", None)
        if session is not None:
            e["CLAUDE_CODE_SESSION_ID"] = session
        e.update(env or {})
        cmd = [sys.executable, "-I", "-S", str(SPUD)] + (["--as", actor] if actor else []) + [str(a) for a in args]
        proc = subprocess.run(cmd, capture_output=True, text=True, env=e, cwd=str(cwd or self.home.path), input=stdin)
        if check and proc.returncode != 0:
            raise AssertionError("spud %s (cwd %s) exited %d\nstdout: %s\nstderr: %s" % (" ".join(cmd[4:]), cwd or self.home.path, proc.returncode, proc.stdout, proc.stderr))
        return proc

    def cli_json(self, *args, **kw):
        proc = self.cli("--json", *args, **kw)
        try:
            return json.loads(proc.stdout)
        except json.JSONDecodeError as e:
            raise AssertionError("not JSON: %r (stderr %r)" % (proc.stdout, proc.stderr)) from e

    def add_project(self, root, key="badtakes", ticket_prefix="BAD", team_prefix="BADS", landing="pr", *extra, check=True):
        return self.cli("project", "add", root, "--key", key, "--ticket-prefix", ticket_prefix, "--team-prefix", team_prefix, "--landing", landing,
                        *extra, actor="spud", check=check)


class HookResult:
    """What a hook run produced: exit code, stdout (parsed as JSON when it is), stderr."""

    def __init__(self, code, stdout, stderr):
        self.code = code
        self.stdout = stdout
        self.stderr = stderr
        self.json = None
        if stdout.strip():
            try:
                self.json = json.loads(stdout)
            except json.JSONDecodeError:
                self.json = None

    @property
    def decision(self):
        """PreToolUse: the permissionDecision, or None when the hook stayed silent."""
        if not self.json:
            return None
        return self.json.get("hookSpecificOutput", {}).get("permissionDecision")

    @property
    def reason(self):
        if not self.json:
            return ""
        return self.json.get("hookSpecificOutput", {}).get("permissionDecisionReason") or self.json.get("reason") or ""

    @property
    def context(self):
        if not self.json:
            return ""
        return self.json.get("hookSpecificOutput", {}).get("additionalContext") or ""

    def __repr__(self):
        return "HookResult(code=%r, stdout=%r, stderr=%r)" % (self.code, self.stdout, self.stderr)


class SpudTestCase(unittest.TestCase):
    """A test case with a fresh initialised Home per test."""

    config = None
    home_name = None

    def setUp(self):
        self.home = Home(config=self.config, name=self.home_name)
        self.addCleanup(self.home.cleanup)
        self.home.init()

    # Small builders used across files.
    def new_ticket(self, title="A ticket", **kw):
        args = ["ticket", "new", "--title", title]
        for k, v in kw.items():
            if isinstance(v, (list, tuple)):
                for item in v:
                    args += ["--" + k.replace("_", "-"), item]
            else:
                args += ["--" + k.replace("_", "-"), v]
        return self.home.json(*args, actor="spud")["ticket"]

    def new_member(self, ticket, actor="spud", persona="scout", model="haiku", **kw):
        kw.setdefault("brief", "Do the thing.")
        args = ["member", "new", "--ticket", ticket, "--persona", persona, "--model", model]
        for k, v in kw.items():
            if isinstance(v, (list, tuple)):
                for item in v:
                    args += ["--" + k.replace("_", "-"), item]
            else:
                args += ["--" + k.replace("_", "-"), v]
        return self.home.json(*args, actor=actor)["member"]


def normalize_markdown(text):
    """The acceptance test's allowed differences: marker line, trailing
    whitespace, runs of blank lines (and blank lines at either end)."""
    out = []
    for line in text.splitlines():
        if line.strip() == MARKER:
            continue
        line = line.rstrip()
        if line == "" and out and out[-1] == "":
            continue
        out.append(line)
    while out and out[0] == "":
        out.pop(0)
    while out and out[-1] == "":
        out.pop()
    return "\n".join(out) + "\n"


# A ticket note's ## Team section is generated from the members table alone since SPD-010
# (docs/design/2026-09-12-team-card.md): a table, the member tree carrying each member's
# worked-on sentence, the embedded Team view.  The round trips compare it by the rule of the
# spec's section 8.3 rather than byte for byte.
TEAM_TABLE_HEADER = "| Member | ID | Persona | Model | Status | Run | Tokens | Cost (list) | Tools |"  # Cost (list) since SPD-013
TEAM_TABLE_DELIMITER = "|---|---|---|---|---|---|---|---|---|"
TEAM_VIEW_EMBED = "![[Fleet.base#Team]]"
WORKED_ON_SUFFIX = " — "


def split_team_section(text):
    """A note without the body of its `## Team` section (the heading line stays), and that body;
    (text, None) for a note that has no such section."""
    lines = text.split("\n")
    if "## Team" not in lines:
        return text, None
    start = lines.index("## Team") + 1
    end = start
    while end < len(lines) and not lines[end].startswith("## "):
        end += 1
    return "\n".join(lines[:start] + lines[end:]), "\n".join(lines[start:end])


def team_section_problems(source, rendered):
    """What is wrong with a rendered `## Team` body against the body it was imported from, [] when
    nothing: the tree lines (lines opening `- [[`), each without its ` — …` suffix, equal the
    source's in order; every source tree line that has a suffix is rendered unchanged; a section
    with members starts with the table header and delimiter and ends with the embed line, and a
    section without members is empty."""

    def tree(text):
        return [line.rstrip() for line in text.split("\n") if line.lstrip().startswith("- [[")]

    def bare(line):
        return line.split(WORKED_ON_SUFFIX, 1)[0]

    want, got = tree(source), tree(rendered)
    problems = []
    if [bare(line) for line in got] != [bare(line) for line in want]:
        problems.append("the tree lines without their suffixes differ: source %r, rendered %r" % ([bare(l) for l in want], [bare(l) for l in got]))
    for i, line in enumerate(want):
        if WORKED_ON_SUFFIX in line and (i >= len(got) or got[i] != line):
            problems.append("the source tree line %r is not rendered unchanged" % line)
    lines = [line.rstrip() for line in rendered.strip("\n").split("\n")] if rendered.strip() else []
    if want or got:
        if lines[:2] != [TEAM_TABLE_HEADER, TEAM_TABLE_DELIMITER]:
            problems.append("the section does not start with the table header and delimiter: %r" % lines[:2])
        if lines[-1:] != [TEAM_VIEW_EMBED]:
            problems.append("the section does not end with the embed line: %r" % lines[-1:])
    elif lines:
        problems.append("a ticket without members renders an empty section, not %r" % rendered)
    return problems
